In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense

In [3]:
sentences = [
 "I love this product",
 "This movie made me smile",
 "Service was friendly and quick",
 "Today felt bright and happy",
 "This is the best day",
 "Absolutely fantastic experience",
 "I enjoyed every single moment",
 "Great job, well done",
 "The food tasted delicious",
 "Totally recommend to everyone",
 "Very satisfied with results",
 "This worked better than expected",
 "Amazing quality and value",
 "Such a pleasant surprise",
 "I feel positive about this",
 "I hate this product",
 "This movie bored me",
 "Service was rude and slow",
 "Today was cold and lonely",
 "This is the worst day",
 "Terrible experience overall",
 "I regret buying this",
 "Very disappointed with results",
 "The food tasted awful",
 "Do not recommend this",
 "It broke after one use",
 "Not worth the money",
 "Utterly frustrating and annoying",
 "I feel negative about this",
 "Such a waste of time",
]
labels = [1]*15 + [0]*15
labels = np.array(labels)

In [4]:
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
vocab_size = 2000
tokenizer = Tokenizer(num_words=vocab_size ,oov_token="<OOV>" )
tokenizer.fit_on_texts(sentences)
sequence = tokenizer.texts_to_sequences(sentences)
maxlen = max(len(s) for s in sequence)
x = pad_sequences(sequence , maxlen=maxlen , padding = "post")
y = labels 

In [58]:
maxlen

5

In [59]:
sequence

[[3, 26, 2, 7],
 [2, 8, 27, 9, 28],
 [10, 6, 29, 4, 30],
 [11, 31, 32, 4, 33],
 [2, 12, 5, 34, 13],
 [35, 36, 14],
 [3, 37, 38, 39, 40],
 [41, 42, 43, 44],
 [5, 15, 16, 45],
 [46, 17, 47, 48],
 [18, 49, 19, 20],
 [2, 50, 51, 52, 53],
 [54, 55, 4, 56],
 [21, 22, 57, 58],
 [3, 23, 59, 24, 2],
 [3, 60, 2, 7],
 [2, 8, 61, 9],
 [10, 6, 62, 4, 63],
 [11, 6, 64, 4, 65],
 [2, 12, 5, 66, 13],
 [67, 14, 68],
 [3, 69, 70, 2],
 [18, 71, 19, 20],
 [5, 15, 16, 72],
 [73, 25, 17, 2],
 [74, 75, 76, 77, 78],
 [25, 79, 5, 80],
 [81, 82, 4, 83],
 [3, 23, 84, 24, 2],
 [21, 22, 85, 86, 87]]

In [60]:
x[0]

array([ 3, 26,  2,  7,  0], dtype=int32)

In [61]:
x[29]

array([21, 22, 85, 86, 87], dtype=int32)

In [62]:
embed_dim = 16
rnn_units = 8


In [63]:
x

array([[ 3, 26,  2,  7,  0],
       [ 2,  8, 27,  9, 28],
       [10,  6, 29,  4, 30],
       [11, 31, 32,  4, 33],
       [ 2, 12,  5, 34, 13],
       [35, 36, 14,  0,  0],
       [ 3, 37, 38, 39, 40],
       [41, 42, 43, 44,  0],
       [ 5, 15, 16, 45,  0],
       [46, 17, 47, 48,  0],
       [18, 49, 19, 20,  0],
       [ 2, 50, 51, 52, 53],
       [54, 55,  4, 56,  0],
       [21, 22, 57, 58,  0],
       [ 3, 23, 59, 24,  2],
       [ 3, 60,  2,  7,  0],
       [ 2,  8, 61,  9,  0],
       [10,  6, 62,  4, 63],
       [11,  6, 64,  4, 65],
       [ 2, 12,  5, 66, 13],
       [67, 14, 68,  0,  0],
       [ 3, 69, 70,  2,  0],
       [18, 71, 19, 20,  0],
       [ 5, 15, 16, 72,  0],
       [73, 25, 17,  2,  0],
       [74, 75, 76, 77, 78],
       [25, 79,  5, 80,  0],
       [81, 82,  4, 83,  0],
       [ 3, 23, 84, 24,  2],
       [21, 22, 85, 86, 87]], dtype=int32)

In [64]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
inp = Input(shape=(maxlen ,), dtype="int32" , name = "input")

In [66]:
x_emb = Embedding(input_dim = vocab_size, output_dim = embed_dim , mask_zero=True , name = "embed")(inp)

In [67]:
rnn = SimpleRNN(units= rnn_units , return_sequences= False , name = 'simple_rnn')

In [68]:
x_last = rnn(x_emb)

out = Dense(1, activation="sigmoid", name="out")(x_last)

model = Model(inputs=inp, outputs=out)

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)            │ (None, 5)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ embed (Embedding)             │ (None, 5, 16)             │          32,000 │ input[0][0]                │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ not_equal_6 (NotEqual)        │ (None, 5)                 │               0 │ input[0][0]                │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ simple_rnn (SimpleRNN)        │ (None, 8)                 │             200 │ embed[0][0],               │
│                               │                           │                 │ not_equal_6[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ out (Dense)                   │ (None, 1)                 │               9 │ simple_rnn[0][0]           │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 32,209 (125.82 KB)

 Trainable params: 32,209 (125.82 KB)

 Non-trainable params: 0 (0.00 B)

In [70]:
model.fit(x , y , epochs = 25 , batch_size = 8 , verbose = 1)

Epoch 1/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.2874
Epoch 2/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2660 
Epoch 3/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2475 
Epoch 4/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2293 
Epoch 5/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2126 
Epoch 6/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1968 
Epoch 7/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.1827
Epoch 8/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.1698
Epoch 9/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.1582
Epoch 10/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.1481
Epoch 11/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.1385
Epoch 12/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1296
E

In [72]:
# Task
# Create an intermediate Keras model to visualize the outputs of the embedding layer and the hidden states of the SimpleRNN layer from the existing model. Then, use this intermediate model to predict on the input data and visualize the outputs.

# Create intermediate model
# Subtask:
# Build a new Keras Model that takes the same input as the original model but outputs the embedding layer and the hidden states of the SimpleRNN layer.

# Reasoning: Define an intermediate Keras model with the same input as the original model and outputs from the embedding and simple RNN layers.


intermediate_model = Model(inputs=model.inputs, outputs=[model.get_layer('embed').output, model.get_layer('simple_rnn').output])
     

from tensorflow.keras.layers import SimpleRNN as SRNN
seq_inp = Input(shape=(maxlen,), dtype='int32')
seq_emb = model.get_layer('embed')(seq_inp)  # reuse trained embedding

# Create RNN with return_sequences=True
rnn_seq = SRNN(units=rnn_units, return_sequences=True, name='rnn_seq')

# DO NOT CALL build() manually
seq_hidden = rnn_seq(seq_emb)  # builds automatically

# Copy trained RNN weights
try:
    trained_weights = model.get_layer('simple_rnn').get_weights()
    rnn_seq.set_weights(trained_weights)
    print("Copied RNN weights into sequence-inspection RNN.")
except Exception as e:
    print("Could not copy weights automatically:", e)

inspect_model = Model(inputs=seq_inp, outputs=seq_hidden)

# Inspect
idx = 0
example_seq = x[idx:idx+1]  # shape (1, maxlen)
hidden_seq = inspect_model.predict(example_seq)

print("Sentence:", sentences[idx])
print("Token ids:", example_seq)
print("Hidden states per timestep shape:", hidden_seq.shape)
print("Hidden states (timesteps x units):")
print(np.round(hidden_seq[0], 3))


Copied RNN weights into sequence-inspection RNN.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
Sentence: I love this product
Token ids: [[ 3 26  2  7  0]]
Hidden states per timestep shape: (1, 5, 8)
Hidden states (timesteps x units):
[[ 0.027  0.008 -0.043  0.005  0.013 -0.021  0.016  0.024]
 [-0.302 -0.383 -0.16  -0.314  0.328 -0.363  0.178 -0.146]
 [ 0.391 -0.71   0.477 -0.216 -0.583  0.469 -0.08  -0.126]
 [-0.854  0.346 -0.665 -0.677 -0.003 -0.62   0.613  0.721]
 [-0.854  0.346 -0.665 -0.677 -0.003 -0.62   0.613  0.721]]
